### ISSUE TITLE
Integration with MessageBus?

### ISSUE THREAD

**Issue by sedubois** [logux/logux_rails#82]
I am not at all familiar with Logux so please dismiss this ticket if it does not make sense, but I saw it uses websockets, which I've read is not necessarily always reliable:
https://discuss.rubyonrails.org/t/actioncable-messaging-doesnt-recover-from-disconnect-reconnect/75074/2
https://samsaffron.com/archive/2015/12/29/websockets-caution-required

Maybe supporting [MessageBus](https://github.com/discourse/message_bus/) could help?

**Comment by ai** [comment]
Yeap, WS is not accessible in some systems. Old gateways are not a problem for WSS (WS over TLS) protocol since gateways do not see a difference with HTTPS.

The most popular case is when old firewalls bunch the network messages, which increase latency and brake ping-pong network check.

We have pure HTTP support in our [Roadmap](https://github.com/logux/logux/projects/1).

---

We can’t use MessageBus for a few reasons:

1. Logux is not just a real-time message system like MessageBus. We are copying the ideas from CRDT and distributed systems to provide conflict-free collaboration. Here is [my recent talk](https://www.youtube.com/watch?v=c7t_YBNHkeo) when I am speaking about benefits from CRDT. Because of it. we have a different channel implementation and many other differences.
2. Logux is not a Rails-only system. We support Django and Node.js. We are doing it by providing a Node.js server, which will proxy CRDT real-time messages to simple HTTP requests. Rails and Django support is just a syntax sugar around this [HTTP requests between Node.js proxy and HTTP server](https://logux.io/protocols/backend/spec/).
